apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-server
  labels:
    app.kubernetes.io/name: terrakojo
    app.kubernetes.io/managed-by: kustomize
rules:
- apiGroups:
  - terrakojo.io
  resources:
  - repositories
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - terrakojo.io
  resources:
  - repositories/status
  verbs:
  - get
  - update
  - patch
