apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-server
  labels:
    app.kubernetes.io/name: terrakojo
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook-server
subjects:
- kind: ServiceAccount
  name: webhook-server
  namespace: system
