# This rule is not used by the project terrakojo itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to terraform.terrakojo.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: terrakojo
    app.kubernetes.io/managed-by: kustomize
  name: terraformrun-viewer-role
rules:
- apiGroups:
  - terraform.terrakojo.io
  resources:
  - terraformruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - terraform.terrakojo.io
  resources:
  - terraformruns/status
  verbs:
  - get
