## Append samples of your project ##
resources:
- v1alpha1_repository.yaml
- v1alpha1_branch.yaml
- v1alpha1_workflow.yaml
- v1alpha1_workflowtemplate.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
