apiVersion: terraform.terrakojo.io/v1alpha1
kind: TerraformRepository
metadata:
  labels:
    app.kubernetes.io/name: terrakojo
    app.kubernetes.io/managed-by: kustomize
  name: terraformrepository-sample
spec:
  # TODO(user): Add fields here
