apiVersion: terrakojo.io/v1alpha1
kind: Workflow
metadata:
  labels:
    app.kubernetes.io/name: terrakojo
    app.kubernetes.io/managed-by: kustomize
  name: workflow-sample
spec:
  owner: "example"
  repository: "terrakojo"
  branch: "feature-auth"
  sha: "0123456789abcdef0123456789abcdef01234567"
  template: "workflowtemplate-sample"
  path: "infra/main.tf"
