apiVersion: terrakojo.io/v1alpha1
kind: WorkflowTemplate
metadata:
  labels:
    app.kubernetes.io/name: terrakojo
    app.kubernetes.io/managed-by: kustomize
  name: workflowtemplate-sample
spec:
  # TODO(user): Add fields here
